# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NewmanRunner CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  newman:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.2]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@master
    - uses: matt-ball/newman-action@master
      with:
          collection: https://postman-echo.com/get?source=newman-sample-github-collection
    - run: npm ci
    - run: npm run build --if-present

